### PR TITLE
some solutions to 1490 added

### PR DESCRIPTION
**Pull request by madhavpcm**
#### Make sure all the item in the checklist have been done before making the PR

- [x] You have starred the repo
- [x] If you have added a new folder, there are no spaces in the name of the folder
- [x] The link to the problem set is present on the first line of the code file
- [x] Your code (solution) in your code file(s) is accepted by the problemset on CodeForces

### CODE REVIEW

**Comment by virejdasani** [comment]
@madhavpcm Please check the spellings of the folder names match the problemset and the first letter of every word in the folder names are capitalized. Please make another PR

**Comment by madhavpcm** [comment]
Hey, since hacktoberfest doesnt count prs after October 31st is it fine that I edit this pr?

**Comment by virejdasani** [comment]
Ok sure

**Comment by madhavpcm** [comment]
- [x] Changed DenseArry_1490A.cpp ->  DenseArray_1490A.cpp
- [x] Removed SumofCubes_1490C.cpp as this solution was already submitted

**Comment by virejdasani** [comment]
@madhavpcm
> Please check the names of the folders match the problemset names

**Comment by madhavpcm** [comment]
> @madhavpcm
> 
> > Please check the names of the folders match the problemset names

my bad, changed
- [x] BalancedReminders-1490B/ to BalancedRemainders-1490B/

**Comment by virejdasani** [comment]
@madhavpcm looks good 👍

**Comment by virejdasani** [comment]
@all-contributors please add @madhavpcm for code

**Comment by madhavpcm** [comment]
Thank you !

**Pull request merged**
