### PR TITLE
added solution of basketballTogether-1725B

### PR DESCRIPTION
**Pull request by shivamsisodia07**
#### Make sure all the item in the checklist have been done before making the PR

- [X] You have starred the repo
- [X] If you have added a new folder, there are no spaces in the name of the folder
- [X] The link to the problem set is present on the first line of the code file
- [X] Your code (solution) in your code file(s) is accepted by the problemset on CodeForces

### CODE REVIEW

**Comment by virejdasani** [comment]
Please read the contribution guidelines and you've named the folder basketball and the file baseball :|

**Comment by shivamsisodia07** [comment]
now, I have changed the pr according to the contribution guidelines.

**Comment by shivamsisodia07** [comment]
@virejdasani please check I have corrected the issue

**Comment by shivamsisodia07** [comment]
@virejdasani please label it as hacktoberfest accepted.

**Comment by virejdasani** [comment]
@shivamsisodia07 It counts towards hacktoberfest even if I don't label it because I merged the PR

**Pull request merged**
